# Generated by Django 3.2.12 on 2022-03-05 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='desc',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='places',
            name='name',
            field=models.CharField(default='SOME STRING', max_length=250),
        ),
    ]
