# Generated by Django 3.2.12 on 2022-03-05 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_auto_20220305_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='ima',
            field=models.ImageField(blank=True, null=True, upload_to='pics_section'),
        ),
    ]
