# Generated by Django 3.2.12 on 2022-03-06 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_places_ima'),
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='write name', max_length=100)),
                ('ima', models.ImageField(blank=True, null=True, upload_to='pics_section')),
                ('desc', models.TextField(null=True)),
            ],
        ),
    ]
